name: Build & publish OpenSearch image from a branch

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: 'AWS region'
        required: true
      ecr_registry_alias:
        description: 'ECR registry alias'
        required: true
      ecr_repository:
        description: 'ECR repository'
        required: true
      target_version:
        description: 'Which version of OpenSearch that this build is targeting'
        required: true
      architecture:
        description: 'Choose architecture'
        type: choice
        required: true
        options:
        - x64
        - arm64
      platform:
        description: 'Choose platform'
        type: choice
        required: true
        options:
        - linux
        - darwin
        - windows
      opensearch_repo:
        description: 'OpenSearch git repository(optional)'
        required: false
      opensearch_ref:
        description: 'OpenSearch git ref(optional)'
        required: false

jobs:
  build-opensearch:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
      JDK_VERSION: 14
      RELEASE_TAG: ${{ github.event.inputs.target_version }}-experimental.${{ github.run_id }}
      TARGET_VERSION: ${{ github.event.inputs.target_version || '2.7.0' }}
      OPENSEARCH_REPO: ${{ github.event.inputs.opensearch_repo || 'https://github.com/msfroh/OpenSearch.git' }}
      OPENSEARCH_REF: ${{ github.event.inputs.opensearch_ref || '2.7_search_pipelines' }}
      ARCH: ${{ github.event.inputs.architecture || 'x64' }}
      PLATFORM: ${{ github.event.inputs.platform || 'linux' }}
      AWS_REGION: ${{ github.event.inputs.aws_region }}
      ECR_REGISTRY_ALIAS: ${{ github.event.inputs.ecr_registry_alias }}
      ECR_REPOSITORY: ${{ github.event.inputs.ecr_repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: opensearch-project/opensearch-build
          path: opensearch-build
      - uses: actions/checkout@v3
        with:
          path: opensearch-dev-env
      - name: Set Up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JDK_VERSION }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
          sudo apt-get install libopenblas-dev gfortran -y
      - name: Update OpenSearch repository
        uses: mikefarah/yq@master
        if: ${{ env.OPENSEARCH_REPO != '' }}
        with:
          cmd: yq -i '.components |= map(select(.name == "OpenSearch").repository="${{ env.OPENSEARCH_REPO }}")' ./opensearch-build/manifests/${{ env.TARGET_VERSION }}/opensearch-${{ env.TARGET_VERSION }}.yml
      - name: Update OpenSearch ref
        uses: mikefarah/yq@master
        if: ${{ env.OPENSEARCH_REF != '' }}
        with:
          cmd: yq -i '.components |= map(select(.name == "OpenSearch").ref="${{ env.OPENSEARCH_REF }}")' ./opensearch-build/manifests/${{ env.TARGET_VERSION }}/opensearch-${{ env.TARGET_VERSION }}.yml
      - name: opensearch-${{ env.TARGET_VERSION }}.yml
        run: |
          cat ./opensearch-build/manifests/${{ env.TARGET_VERSION }}/opensearch-${{ env.TARGET_VERSION }}.yml
      - name: Build and assemble
        run: |
          cd opensearch-build
          ./build.sh manifests/${{ env.TARGET_VERSION }}/opensearch-${{ env.TARGET_VERSION }}.yml --architecture ${{ env.ARCH }} --platform ${{ env.PLATFORM }}
          ./assemble.sh tar/builds/opensearch/manifest.yml
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      - name: Build and push docker image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: ${{ env.ECR_REGISTRY_ALIAS }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          artifact_name=opensearch-${{ env.TARGET_VERSION}}-${{ env.PLATFORM }}-${{ env.ARCH }}.tar.gz
          tarball=$(realpath opensearch-build/tar/dist/opensearch/$artifact_name)
          cd ./opensearch-build/docker/release
          ./build-image-single-arch.sh -v $IMAGE_TAG -p opensearch -a ${{ env.ARCH }} -f ${{ github.workspace }}/opensearch-dev-env/docker/opensearch.dockerfile -t $tarball
          docker images
          docker tag opensearchproject/opensearch:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          echo "Pushed docker image: $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG"
